//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public long ID { get; set; }
        public long CartId { get; set; }
        public long ItemId { get; set; }
        public long Quantity { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
